import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'ai_service.dart';
import 'guide_store.dart';

class AiStudyGuidePage extends StatefulWidget { const AiStudyGuidePage({super.key, required this.store}); final GuideStore store; @override State<AiStudyGuidePage> createState() => _AiStudyGuidePageState(); }
class _AiStudyGuidePageState extends State<AiStudyGuidePage> {
  int selected = 0; String result = ''; bool busy = false;
  Future<void> load() async { if (widget.store.guides.isEmpty) return; final p = await SharedPreferences.getInstance(); setState(() => result = p.getString('ai_guide_${widget.store.guides[selected].id}') ?? ''); }
  Future<void> generate() async { if (widget.store.guides.isEmpty) return; final g = widget.store.guides[selected]; final p = await SharedPreferences.getInstance(); setState(() => busy = true); try { final text = g.text.length > 24000 ? g.text.substring(0, 24000) : g.text; result = await AiService.askConfigured(prompt: 'Crea una guía de estudio completa en español usando SOLAMENTE este contenido. Organízala con: 1) objetivos de aprendizaje, 2) índice de temas, 3) conceptos esenciales explicados sencillamente, 4) ejemplos presentes o derivados directamente del texto, 5) vocabulario clave, 6) errores o confusiones frecuentes, 7) preguntas de práctica, 8) lista final de lo que el estudiante debe dominar. No inventes datos externos. Título: ${g.title}\nCONTENIDO:\n$text'); await p.setString('ai_guide_${g.id}', result); } catch (e) { result = 'No pude generar la guía: $e'; } finally { if (mounted) setState(() => busy = false); } }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Guía de estudio')), body: widget.store.guides.isEmpty ? const Center(child: Text('Añade primero un documento.')) : ListView(padding: const EdgeInsets.all(16), children: [DropdownButtonFormField<int>(initialValue: selected, items: [for (int i = 0; i < widget.store.guides.length; i++) DropdownMenuItem(value: i, child: Text(widget.store.guides[i].title, overflow: TextOverflow.ellipsis))], onChanged: (v) { setState(() { selected = v ?? 0; result = ''; }); load(); }, decoration: const InputDecoration(labelText: 'Contenido para la guía')), const SizedBox(height: 14), FilledButton.icon(onPressed: busy ? null : generate, icon: const Icon(Icons.auto_awesome), label: Text(busy ? 'Creando guía…' : 'Crear guía de estudio')), if (result.isNotEmpty) Card(child: Padding(padding: const EdgeInsets.all(18), child: SelectableText(result, style: const TextStyle(height: 1.5))))]));
}
