import 'dart:convert';
import 'dart:math';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'ai_service.dart';
import 'guide_store.dart';
import 'tutor_context_service.dart';

const _channel = MethodChannel('com.memora/daily_exam_headless');
const _storageKey = 'memora_tutor_exams_v1';
String _today(){final d=DateTime.now();return '${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';}
List<Map<String,dynamic>> _parse(String raw){try{final a=raw.indexOf('['),b=raw.lastIndexOf(']');if(a<0||b<=a)return [];final v=jsonDecode(raw.substring(a,b+1));if(v is! List)return [];return v.whereType<Map>().map((x){final m=Map<String,dynamic>.from(x);return {'question':(m['question']??m['pregunta']??'').toString().trim(),'answer':(m['answer']??m['respuesta']??'').toString().trim(),'sourceTitle':(m['source']??m['fuente']??'Contenido del tutor').toString().trim()};}).where((x)=>x['question'].toString().isNotEmpty&&x['answer'].toString().isNotEmpty).toList();}catch(_){return [];}}
Future<Map<String,dynamic>> _build(GuideStore store,dynamic tutor,int count,String difficulty,String mode) async{
 final guides=TutorContextService.guidesFor(store,tutor);if(guides.isEmpty)throw Exception('No material');final fallback=<Map<String,dynamic>>[];for(final g in guides){for(final c in g.cards){if(c.question.trim().isNotEmpty&&c.answer.trim().isNotEmpty)fallback.add({'question':c.question.trim(),'answer':c.answer.trim(),'sourceTitle':g.title});}}fallback.shuffle(Random());var qs=<Map<String,dynamic>>[];var label='Instantáneo • contenido indexado';
 if(mode!='instant'){String provider;if(mode=='best'){provider=(await TutorContextService.bestAvailableProvider())??'global';label='Mejor IA disponible • ${TutorContextService.sourceLabel(provider)}';}else{provider=tutor.modelSource.toString();label='${tutor.name} • ${TutorContextService.sourceLabel(provider)}';}final localish=['private','shared','device','local','ollama'].contains(provider);final n=min(count,localish?10:20);final content=TutorContextService.contentForGuides(guides,maxChars:localish?12000:24000);try{final raw=await AiService.askConfigured(providerOverride:provider,responseMode:localish?'normal':'deep',prompt:'''Crea un examen de $n preguntas basado EXCLUSIVAMENTE en el contenido del tutor ${tutor.name}.\nDificultad: $difficulty.\nEvalúa comprensión real. No uses conocimiento externo. Devuelve SOLO JSON válido: [{"question":"...","answer":"...","source":"..."}].\nCONTENIDO:\n$content''');qs=_parse(raw);}catch(_){qs=[];}}
 final seen=qs.map((x)=>x['question'].toString().toLowerCase()).toSet();for(final x in fallback){if(qs.length>=count)break;if(seen.add(x['question'].toString().toLowerCase()))qs.add(x);}if(qs.length>count)qs=qs.take(count).toList();if(qs.isEmpty)throw Exception('No questions');final now=DateTime.now();return {'id':'exam_${now.microsecondsSinceEpoch}','tutorId':tutor.id,'tutorName':tutor.name,'tutorEmoji':tutor.emoji,'createdAt':now.toIso8601String(),'dateKey':_today(),'isDaily':true,'difficulty':difficulty,'generatorLabel':label,'questions':qs,'currentIndex':0,'correct':0,'completed':false};
}
@pragma('vm:entry-point')
Future<void> dailyExamHeadlessMain() async{try{final prefs=await SharedPreferences.getInstance();if(!(prefs.getBool('daily_exam_auto_enabled')??false)){await _channel.invokeMethod('complete');return;}final store=GuideStore();await store.load();final tutors=await TutorContextService.loadProfiles();final raw=prefs.getString(_storageKey);var sessions=<dynamic>[];try{final x=raw==null?null:jsonDecode(raw);if(x is List)sessions=List<dynamic>.from(x);}catch(_){}final today=_today();final mode=prefs.getString('daily_exam_generator')??'best';final difficulty=prefs.getString('daily_exam_difficulty')??'Adaptativa';final count=prefs.getInt('daily_exam_count')??10;var failed=false;for(final tutor in tutors){final guides=TutorContextService.guidesFor(store,tutor);if(guides.isEmpty)continue;final enabled=prefs.getBool('daily_exam_tutor_enabled_${tutor.id}')??true;if(!enabled)continue;final exists=sessions.any((e)=>e is Map&&e['isDaily']==true&&e['tutorId']==tutor.id&&e['dateKey']==today);if(exists){await prefs.setString('daily_exam_last_tutor_${tutor.id}',today);continue;}try{final exam=await _build(store,tutor,count,difficulty,mode);sessions.removeWhere((e)=>e is Map&&e['isDaily']==true&&e['tutorId']==tutor.id&&e['dateKey']==today);sessions.insert(0,exam);await prefs.setString(_storageKey,jsonEncode(sessions));await prefs.setString('daily_exam_last_tutor_${tutor.id}',today);}catch(_){failed=true;}}await prefs.setBool('daily_exam_auto_pending',failed);if(!failed)await prefs.setString('daily_exam_auto_last_run',today);}catch(_){try{final p=await SharedPreferences.getInstance();await p.setBool('daily_exam_auto_pending',true);}catch(_){}}finally{try{await _channel.invokeMethod('complete');}catch(_){}}}
