import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'ai_service.dart';
import 'guide_store.dart';

class StudyPlanPage extends StatefulWidget{const StudyPlanPage({super.key,required this.store});final GuideStore store;@override State<StudyPlanPage> createState()=>_StudyPlanPageState();}
class _StudyPlanPageState extends State<StudyPlanPage>{final goal=TextEditingController();final minutes=TextEditingController(text:'45');String intensity='Normal';bool dated=false;String plan='';bool busy=false;
Future<void> generate()async{if(widget.store.guides.isEmpty)return;final p=await SharedPreferences.getInstance();final key=p.getString('gemini_key');final guide=widget.store.guides.first;setState(()=>busy=true);try{final prompt='Crea en español un plan para aprender y dominar este contenido. Objetivo: ${goal.text}. Minutos diarios: ${minutes.text}. Intensidad: $intensity. Modalidad: ${dated?'preparación con fecha':'aprendizaje continuo para la vida'}. Incluye acciones diarias, revisión semanal, metas mensuales, trimestrales y anuales; mezcla contenido nuevo, práctica, pruebas y repetición espaciada. Documento: ${guide.title}\n${guide.text.length>20000?guide.text.substring(0,20000):guide.text}';plan=(key==null||key.isEmpty)?'Configura primero la clave de Gemini desde la pantalla Tutor.':await AiService.ask(apiKey:key,prompt:prompt);}catch(e){plan='No pude crear el plan: $e';}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Mi plan de aprendizaje')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:goal,decoration:const InputDecoration(labelText:'¿Qué quieres llegar a dominar?')),const SizedBox(height:12),TextField(controller:minutes,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Minutos disponibles por día')),SwitchListTile(value:dated,onChanged:(v)=>setState(()=>dated=v),title:Text(dated?'Tengo una fecha objetivo':'Aprendizaje continuo')),DropdownButtonFormField(value:intensity,items:['Tranquila','Normal','Intensiva'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>intensity=v??'Normal'),decoration:const InputDecoration(labelText:'Intensidad')),const SizedBox(height:16),FilledButton.icon(onPressed:busy?null:generate,icon:const Icon(Icons.auto_awesome),label:Text(busy?'Creando…':'Crear mi plan')),if(plan.isNotEmpty)Card(child:Padding(padding:const EdgeInsets.all(18),child:SelectableText(plan))) ]));}
