import 'package:flutter/material.dart';
import 'ai_service.dart';
import 'guide_store.dart';
import 'llm_settings_page.dart';

class TutorPage extends StatefulWidget { const TutorPage({super.key, required this.store}); final GuideStore store; @override State<TutorPage> createState() => _TutorPageState(); }
class _TutorPageState extends State<TutorPage> {
  final q = TextEditingController(); String answer = 'Selecciona una guía y pregúntame cualquier cosa que aparezca en ella.'; int selected = 0; bool busy = false;
  Future<void> _settings() async => Navigator.push(context, MaterialPageRoute(builder: (_) => const LlmSettingsPage()));
  Future<void> _ask() async { if (widget.store.guides.isEmpty || q.text.trim().isEmpty) return; final guide = widget.store.guides[selected.clamp(0, widget.store.guides.length - 1)]; setState(() => busy = true); try { final text = guide.text.length > 24000 ? guide.text.substring(0, 24000) : guide.text; final r = await AiService.askConfigured(prompt: 'Eres un tutor. Responde SOLO con la información del documento. Si no aparece, dilo claramente. Explica de manera sencilla y cita el título.\nDOCUMENTO: ${guide.title}\n$text\nPREGUNTA: ${q.text}'); if (mounted) setState(() => answer = r); } catch (e) { if (mounted) setState(() => answer = 'No pude consultar la IA: $e'); } finally { if (mounted) setState(() => busy = false); } }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Tutor con IA'), actions: [IconButton(onPressed: _settings, tooltip: 'Elegir IA online o local', icon: const Icon(Icons.tune))]), body: ListView(padding: const EdgeInsets.all(16), children: [if (widget.store.guides.isEmpty) const Text('Añade primero una guía a tu biblioteca.') else DropdownButtonFormField<int>(initialValue: selected, items: [for (int i = 0; i < widget.store.guides.length; i++) DropdownMenuItem(value: i, child: Text(widget.store.guides[i].title, overflow: TextOverflow.ellipsis))], onChanged: (v) => setState(() => selected = v ?? 0)), const SizedBox(height: 16), Card(child: Padding(padding: const EdgeInsets.all(18), child: Text(answer))), const SizedBox(height: 12), TextField(controller: q, minLines: 2, maxLines: 5, decoration: InputDecoration(hintText: 'Pregunta sobre el documento…', suffixIcon: IconButton(onPressed: busy ? null : _ask, icon: busy ? const Padding(padding: EdgeInsets.all(12), child: CircularProgressIndicator()) : const Icon(Icons.send))))]));
}
