import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'ai_service.dart';
import 'guide_store.dart';

class TutorPage extends StatefulWidget { const TutorPage({super.key,required this.store}); final GuideStore store; @override State<TutorPage> createState()=>_TutorPageState(); }
class _TutorPageState extends State<TutorPage>{
  final q=TextEditingController(); String answer='Selecciona una guía y pregúntame cualquier cosa que aparezca en ella.'; int selected=0; bool busy=false;
  Future<String?> _key() async { final p=await SharedPreferences.getInstance(); return p.getString('gemini_key'); }
  Future<void> _saveKey() async { final c=TextEditingController(text:await _key()); if(!mounted)return; final ok=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:const Text('Clave de Gemini'),content:TextField(controller:c,obscureText:true,decoration:const InputDecoration(labelText:'API key de Google AI Studio')),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Guardar'))])); if(ok==true){final p=await SharedPreferences.getInstance();await p.setString('gemini_key',c.text.trim());}}
  Future<void> _ask() async { if(widget.store.guides.isEmpty||q.text.trim().isEmpty)return; final guide=widget.store.guides[selected.clamp(0,widget.store.guides.length-1)]; final key=await _key(); if(key==null||key.isEmpty){await _saveKey();return;} setState(()=>busy=true); try{final text=guide.text.length>24000?guide.text.substring(0,24000):guide.text; final r=await AiService.ask(apiKey:key,prompt:'Eres un tutor. Responde SOLO con la información del documento. Si no aparece, dilo claramente. Explica de manera sencilla y cita el título.\nDOCUMENTO: ${guide.title}\n$text\nPREGUNTA: ${q.text}'); if(mounted)setState(()=>answer=r);}catch(e){if(mounted)setState(()=>answer='No pude consultar la IA: $e');}finally{if(mounted)setState(()=>busy=false);}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Tutor con IA'),actions:[IconButton(onPressed:_saveKey,icon:const Icon(Icons.key))]),body:ListView(padding:const EdgeInsets.all(16),children:[if(widget.store.guides.isEmpty)const Text('Añade primero una guía a tu biblioteca.')else DropdownButtonFormField<int>(initialValue:selected,items:[for(int i=0;i<widget.store.guides.length;i++)DropdownMenuItem(value:i,child:Text(widget.store.guides[i].title,overflow:TextOverflow.ellipsis))],onChanged:(v)=>setState(()=>selected=v??0)),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(18),child:Text(answer))),const SizedBox(height:12),TextField(controller:q,minLines:2,maxLines:5,decoration:InputDecoration(hintText:'Pregunta sobre el documento…',suffixIcon:IconButton(onPressed:busy?null:_ask,icon:busy?const CircularProgressIndicator():const Icon(Icons.send))))]));
}
